services:
  app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - "./app:/app"
    command: 
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
    depends_on:
      - redis
      - db  



  db:
    image: postgres:alpine
    volumes:
      - chat-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data  # Persist Redis data

volumes:
  chat-db-data:     
  chat-static-data:
  redis-data: